name: Deploy to GitHub Pages
  on:
    push:
      branches:
        - master
    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Setup Pages
          uses: actions/configure-pages@v5
        - name: Build
          run: |
            npm install
            npm run build
          env:
            VITE_FIREBASE_APIKEY: ${{ secrets.VITE_FIREBASE_APIKEY }}
            VITE_FIREBASE_AUTHDOMAIN: ${{ secrets.VITE_FIREBASE_AUTHDOMAIN }}
            VITE_FIREBASE_DATABASEURL: ${{ secrets.VITE_FIREBASE_DATABASEURL }}
            VITE_FIREBASE_PROJECTID: ${{ secrets.VITE_FIREBASE_PROJECTID }}
            VITE_FIREBASE_STORAGEBUCKET: ${{ secrets.VITE_FIREBASE_STORAGEBUCKET }}
            VITE_FIREBASE_MESSAGINGSENDERID: ${{ secrets.VITE_FIREBASE_MESSAGINGSENDERID }}
            VITE_FIREBASE_APPID: ${{ secrets.VITE_FIREBASE_APPID }}
        - name: Deploy
          uses: actions/deploy-pages@v4
          with:
            BRANCH: main
            FOLDER: dist
